In [1]:
from wbot import read,play
import numpy as np

plist=read.word_list('possible')
glist=read.word_list('allowed')


big_arr=[]

for i, g in enumerate(glist):
    small_arr=[]
    for j,p in enumerate(plist):
        small_arr+=[play.tiles(p,g)]
    
    big_arr+=[small_arr]
    
    if i%100==0:
        print(i)



big_arr=np.array(big_arr)

#np.save('tile_gird.npy',big_arr)

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900


In [2]:
def reduce(guess,tiles,tgrid,plist,glist):
    
    
    g_id=np.where(glist==guess)[0][0]

    w=np.where(np.prod(tgrid[g_id,:,:] == tiles, axis = -1))[0]
    
    return tgrid[:,w,:],plist[w]



def prob_grid(tgrid):
    
    gs,ps,_=tgrid.shape
    
    egrid=np.zeros(gs)
    
    for i in range(gs):
        
        un_pat=np.unique(tgrid[i,:,:],axis=0)
        mean_inf=0
        
        for j in range(un_pat.shape[0]):
            
           
            p=len(np.where(np.prod(tgrid[i,:,:] == un_pat[j,:], axis = -1))[0])/ps
            mean_inf+=-p*np.log2(p)

        egrid[i]=mean_inf
    return egrid

def cut_off(w,tgrid,plist,glist,igrid,count):
    ids=[]
    info_list=[]
    for p in plist:
        
        ids=np.where(glist==p)[0][0]
        
        info_list+=[igrid[ids]]
    
    guess=plist[np.argmax(info_list)]
    
    count+=1
    tiles=play.tiles(w,guess)
    if tiles==[2,2,2,2,2]:
        print(w,guess,count)
        return count        
    else:
        tgrid,plist_=reduce(guess,tiles,tgrid,plist,glist)
        
        if len(plist_)==1:
            count+=1
            print(w,plist_[0],count)
            return count
        else:
            return cut_off(w,tgrid,plist_,glist,igrid,count)
        
def manual_cut_off(tgrid,plist,glist,igrid):
    
    print('Possible Answers:', len(plist))
    ids=[]
    info_list=[]
    for p in plist:
        
        ids=np.where(glist==p)[0][0]
        
        info_list+=[igrid[ids]]
    
    guess=plist[np.argmax(info_list)]
    print('Guess:',guess)

    ts=input('Type Tiles')
    if [int(ts[0]),int(ts[1]),int(ts[2]),int(ts[3]),int(ts[4])]==[2,2,2,2,2]:
        print('Done')     
    else:
        tgrid,plist_=reduce(guess,[int(ts[0]),int(ts[1]),int(ts[2]),int(ts[3]),int(ts[4])],tgrid,plist,glist)
        if len(plist_)==1:
            print('Answer:', plist_[0])
        else:
            manual_cut_off(tgrid,plist_,glist,igrid)
                       

In [48]:
print(np.where(np.array(glist)=='salet'))

print(glist[12489])

(array([12489]),)
salet


In [49]:

un_pat=np.unique(big_arr[12489,:,:],axis=0)


g_word=[]
for pat in un_pat:
    
    print(pat)
    
    tgrid,plist_=reduce('salet',pat,big_arr,np.array(plist),np.array(glist))

    x=prob_grid(tgrid)

    guess=glist[np.argmax(x)]
    
    g_word+=[guess]
    
    print(pat,guess)
    

    

[0 0 0 0 0]
[0 0 0 0 0] cornu
[0 0 0 0 1]
[0 0 0 0 1] north
[0 0 0 0 2]
[0 0 0 0 2] groin
[0 0 0 1 0]
[0 0 0 1 0] drone
[0 0 0 1 1]
[0 0 0 1 1] trite
[0 0 0 1 2]
[0 0 0 1 2] curio
[0 0 0 2 0]
[0 0 0 2 0] nidor
[0 0 0 2 1]
[0 0 0 2 1] mohur
[0 0 0 2 2]
[0 0 0 2 2] cerne
[0 0 1 0 0]
[0 0 1 0 0] courd
[0 0 1 0 1]
[0 0 1 0 1] wroth
[0 0 1 0 2]
[0 0 1 0 2] bling
[0 0 1 1 0]
[0 0 1 1 0] beige
[0 0 1 1 1]
[0 0 1 1 1] shute
[0 0 1 1 2]
[0 0 1 1 2] swack
[0 0 1 2 0]
[0 0 1 2 0] livor
[0 0 1 2 1]
[0 0 1 2 1] women
[0 0 1 2 2]
[0 0 1 2 2] women
[0 0 2 0 0]
[0 0 2 0 0] doily
[0 0 2 0 1]
[0 0 2 0 1] nikau
[0 0 2 0 2]
[0 0 2 0 2] women
[0 0 2 1 0]
[0 0 2 1 0] himbo
[0 0 2 1 1]
[0 0 2 1 1] nikau
[0 0 2 2 0]
[0 0 2 2 0] mudge
[0 0 2 2 2]
[0 0 2 2 2] women
[0 1 0 0 0]
[0 1 0 0 0] brond
[0 1 0 0 1]
[0 1 0 0 1] tronc
[0 1 0 0 2]
[0 1 0 0 2] crudo
[0 1 0 1 0]
[0 1 0 1 0] beard
[0 1 0 1 1]
[0 1 0 1 1] grace
[0 1 0 1 2]
[0 1 0 1 2] crena
[0 1 0 2 0]
[0 1 0 2 0] unred
[0 1 0 2 1]
[0 1 0 2 1] women
[0 1 1 0 0

In [4]:
np.save('salet_patterns.npy',un_pat)
np.save('salet_guess.npy',g_word,)

NameError: name 'un_pat' is not defined

In [43]:
print(tgrid.shape)

(12947, 0, 5)


In [ ]:
res=[]
#sal_patterns=np.load('salet_patterns.npy')
#sal_guess=np.load('salet_guess.npy')
for i,w in enumerate(plist):
    
    ts=play.tiles(w,'salet')
    
    tgrid,plist_=reduce('salet',ts,big_arr,np.array(plist),np.array(glist))

    guess=sal_guess[np.where(np.prod(sal_patterns ==ts, axis = -1))[0][0]]

    count=1

    while len(plist_)>6:
        
        count+=1
        
        ts=play.tiles(w,guess)
        
        tgrid,plist_=reduce(guess,ts,tgrid,plist_,np.array(glist))
        
        if ts!=[2,2,2,2,2]:
            
            x=prob_grid(tgrid)

            guess=glist[np.argmax(x)]
        else:
            break
            
    
    if ts==[2,2,2,2,2]:
        print(w,guess,count)
    elif count==1:
        x=prob_grid(tgrid)
        count=cut_off(w,tgrid,plist_,np.array(glist),x,count)  
    
    else:
        count=cut_off(w,tgrid,plist_,np.array(glist),x,count) 
    res+=[count]
    print(np.mean(res))
        

aback aback 3
3.0
abase abase 3
3.0


In [29]:
# print('Guess: salet')
ts=input('Type Tiles:')

tgrid,plist_=reduce('salet',[int(ts[0]),int(ts[1]),int(ts[2]),int(ts[3]),int(ts[4])],big_arr,np.array(plist),np.array(glist))

x=prob_grid(tgrid)

guess=glist[np.argmax(x)]

while len(plist_)>5 or [int(ts[0]),int(ts[1]),int(ts[2]),int(ts[3]),int(ts[4])]!=[2,2,2,2,2]:
    
    print('')
    print('Possible Answers', len(plist_))
    print('Next Guess: ',guess)
    
    ts=input('Type Tiles:')

    tgrid,plist_=reduce(guess,[int(ts[0]),int(ts[1]),int(ts[2]),int(ts[3]),int(ts[4])],tgrid,plist_,np.array(glist))
    
    x=prob_grid(tgrid)

    guess=glist[np.argmax(x)]


    
    
manual_cut_off(tgrid,plist_,np.array(glist),x)   



KeyboardInterrupt: Interrupted by user

In [102]:
x=prob_grid(big_arr)

In [98]:
print(x[np.argmax(x)])
print(glist[np.argmax(x)])


5.885202744292758
soare


In [4]:
import numpy as np


big_arr=np.array(big_arr)

un_pat=np.unique(big_arr.reshape(big_arr.shape[0]**2,5),axis=0)


p=0
for i in range(len(un_pat)):
    p+=len(np.where(np.prod(big_arr == un_pat[i,:], axis = -1))[0])/(big_arr.shape[0])**2
print(p)

0.9999999999999991


In [24]:
play.tiles('homer','homer'

[2, 2, 2, 2, 2]

In [35]:
import numpy as np
ll=np.array([[6,5,4],[4,5,6],[4,5,6]])


print(np.where(np.prod(ll == [4,5,6], axis = -1)))



(array([1, 2]),)


In [ ]:
data = np.array( [  [1,2] , [1,3] ,[3,4], [1,2] , [0,9] ])

In [117]: np.where(np.prod(data == [1,2], axis = -1))
Out[117]: (array([0, 3]),)


False