In [1]:
from wbot import read,play
import numpy as np

plist=read.word_list('possible')
glist=read.word_list('allowed')


big_arr=[]

for i, g in enumerate(glist):
    small_arr=[]
    for j,p in enumerate(plist):
        small_arr+=[play.tiles(p,g)]
    
    big_arr+=[small_arr]
    
    if i%100==0:
        print(i)



big_arr=np.array(big_arr)

#np.save('tile_gird.npy',big_arr)

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900


In [232]:
print(big_arr.shape)
print(np.unique(big_arr[0,:,:],axis=0))

(12947, 2309, 5)
[[0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 2]
 [0 0 0 1 0]
 [0 0 0 1 1]
 [0 0 0 1 2]
 [0 0 0 2 0]
 [0 0 0 2 1]
 [0 0 0 2 2]
 [0 0 1 0 0]
 [0 0 1 0 1]
 [0 0 1 1 0]
 [0 0 1 1 1]
 [0 0 1 2 0]
 [0 0 1 2 1]
 [0 0 2 0 0]
 [0 0 2 0 1]
 [0 0 2 0 2]
 [0 0 2 1 0]
 [0 0 2 2 0]
 [0 0 2 2 1]
 [0 0 2 2 2]
 [0 1 0 0 0]
 [0 1 0 0 1]
 [0 1 0 0 2]
 [0 1 0 1 0]
 [0 1 0 1 1]
 [0 1 0 1 2]
 [0 1 0 2 0]
 [0 1 0 2 1]
 [0 1 0 2 2]
 [0 1 1 0 0]
 [0 1 1 0 1]
 [0 1 1 0 2]
 [0 1 1 1 0]
 [0 1 1 1 1]
 [0 1 1 1 2]
 [0 1 2 0 0]
 [0 1 2 1 0]
 [0 1 2 1 2]
 [0 1 2 2 0]
 [0 2 0 0 0]
 [0 2 0 0 1]
 [0 2 0 0 2]
 [0 2 0 1 0]
 [0 2 0 1 1]
 [0 2 0 2 0]
 [0 2 0 2 1]
 [0 2 0 2 2]
 [0 2 1 0 0]
 [0 2 1 0 1]
 [0 2 1 0 2]
 [0 2 1 1 0]
 [0 2 1 2 0]
 [0 2 1 2 1]
 [0 2 2 0 0]
 [0 2 2 0 1]
 [0 2 2 2 0]
 [1 0 0 0 0]
 [1 0 0 0 1]
 [1 0 0 0 2]
 [1 0 0 1 0]
 [1 0 0 1 1]
 [1 0 0 2 0]
 [1 0 0 2 1]
 [1 0 1 0 0]
 [1 1 0 0 0]
 [1 1 0 0 1]
 [1 1 0 0 2]
 [1 1 0 1 0]
 [1 1 0 1 1]
 [1 1 0 2 1]
 [1 2 0 0 0]
 [1 2 0 0 1]
 [1 2 0 2 0]
 [1 2 1 

In [3]:



def reduce(guess,tiles,tgrid,plist,glist):
    
    
    g_id=np.where(glist==guess)[0][0]

    w=np.where(np.prod(tgrid[g_id,:,:] == tiles, axis = -1))[0]
    
    return tgrid[:,w,:],plist[w]



def prob_grid(tgrid):
    
    gs,ps,_=tgrid.shape
    
    egrid=np.zeros(gs)
    
    for i in range(gs):
        
        un_pat=np.unique(tgrid[i,:,:],axis=0)
        #prob_row=np.zeros(ps)
        mean_inf=0
        
        for j in range(un_pat.shape[0]):
            
           
            p=len(np.where(np.prod(tgrid[i,:,:] == un_pat[j,:], axis = -1))[0])/ps
            mean_inf+=-p*np.log2(p)
            
            
            
        egrid[i]=mean_inf
    return egrid
            

    
        
    
    

In [ ]:
res=[]
for i,w in enumerate(plist):
    tgrid,plist_=reduce('salet',play.tiles(w,'salet'),big_arr,np.array(plist),np.array(glist))

    x=prob_grid(tgrid)

    guess=glist[np.argmax(x)]

    
    count=1

    while len(plist_)>2:
        
        count+=1

        tgrid,plist_=reduce(guess,play.tiles(w,guess),tgrid,plist_,np.array(glist))

        x=prob_grid(tgrid)

        guess=glist[np.argmax(x)]
        
    
    if play.tiles(w,plist_[0])==[2,2,2,2,2]:
        
        count+=1
        print(w,plist_[0],count)
    else:
        count+=2
        print(w,plist_[1],count)
        
        
        
    res+=[count]
    print(np.mean(res))
        

aback aback 3
3.0
abase abase 3
3.0
abate abate 3
3.0
abbey abbey 3
3.0
abbot abbot 3
3.0
abhor abhor 3
3.0
abide abide 4
3.142857142857143
abled abled 2
3.0
abode abode 4
3.111111111111111
abort abort 3
3.1
about about 3
3.090909090909091
above above 3
3.0833333333333335
abuse abuse 3
3.076923076923077
abyss abyss 3
3.0714285714285716
acorn acorn 3
3.066666666666667
acrid acrid 4
3.125
actor actor 3
3.1176470588235294
acute acute 3
3.111111111111111
adage adage 3
3.1052631578947367
adapt adapt 3
3.1
adept adept 3
3.0952380952380953
admin admin 3
3.090909090909091
admit admit 4
3.130434782608696
adobe adobe 4
3.1666666666666665
adopt adopt 3
3.16
adore adore 3
3.1538461538461537
adorn adorn 3
3.1481481481481484
adult adult 3
3.142857142857143
affix affix 4
3.1724137931034484
afire afire 4
3.2
afoot afoot 4
3.225806451612903
afoul afoul 4
3.25
after after 2
3.212121212121212
again again 4
3.235294117647059
agape agape 4
3.257142857142857
agate agate 3
3.25
agent agent 3
3.24324324324324

bravo bravo 3
3.387218045112782
brawl brawl 4
3.3895131086142323
brawn brawn 4
3.3917910447761193
bread bread 3
3.390334572490706
break break 3
3.388888888888889
breed breed 4
3.3911439114391144
briar briar 3
3.389705882352941
bribe bribe 4
3.391941391941392
brick brick 3
3.3905109489051095
bride bride 4
3.3927272727272726
brief brief 3
3.391304347826087
brine brine 4
3.3935018050541514
bring bring 4
3.3956834532374103
brink brink 4
3.3978494623655915
briny briny 4
3.4
brisk brisk 3
3.398576512455516
broad broad 3
3.397163120567376
broil broil 4
3.3992932862190814
broke broke 4
3.4014084507042255
brood brood 4
3.4035087719298245
brook brook 4
3.4055944055944054
broom broom 5
3.4111498257839723
broth broth 3
3.4097222222222223
brown brown 4
3.411764705882353
brunt brunt 3
3.410344827586207
brush brush 3
3.40893470790378
brute brute 3
3.4075342465753424
buddy buddy 4
3.409556313993174
budge budge 4
3.4115646258503403
buggy buggy 4
3.4135593220338984
bugle bugle 3
3.4121621621621623
build

death death 4
3.4597701149425286
debar debar 3
3.458891013384321
debit debit 4
3.4599236641221376
debug debug 3
3.459047619047619
debut debut 3
3.458174904942966
decal decal 4
3.4592030360531307
decay decay 3
3.4583333333333335
decor decor 3
3.4574669187145557
decoy decoy 3
3.456603773584906
decry decry 4
3.457627118644068
defer defer 3
3.456766917293233
deign deign 3
3.455909943714822
deity deity 3
3.455056179775281
delay delay 3
3.4542056074766356
delta delta 2
3.451492537313433
delve delve 3
3.450651769087523
demon demon 3
3.449814126394052
demur demur 4
3.450834879406308
denim denim 4
3.4518518518518517
dense dense 3
3.4510166358595193
depot depot 3
3.4501845018450186
depth depth 4
3.451197053406998
derby derby 4
3.452205882352941
deter deter 4
3.453211009174312
detox detox 3
3.4523809523809526
deuce deuce 3
3.4515539305301646
devil devil 3
3.4507299270072993
diary diary 3
3.4499089253187614
dicey dicey 3
3.449090909090909
digit digit 3
3.4482758620689653
dilly dilly 3
3.4474637681

flume flume 4
3.457474226804124
flung flung 4
3.458172458172458
flunk flunk 4
3.4588688946015425
flush flush 3
3.4582798459563544
flute flute 3
3.457692307692308
flyer flyer 4
3.458386683738796
foamy foamy 4
3.459079283887468
focal focal 4
3.4597701149425286
focus focus 3
3.4591836734693877
foggy foggy 4
3.4598726114649683
foist foist 4
3.460559796437659
folio folio 3
3.45997458703939
folly folly 4
3.4606598984771573
foray foray 4
3.461343472750317
force force 4
3.462025316455696
forge forge 4
3.4627054361567637
forgo forgo 4
3.4633838383838382
forte forte 3
3.462799495586381
forth forth 3
3.4622166246851385
forty forty 3
3.4616352201257863
forum forum 3
3.4610552763819094
found found 5
3.4629861982434127
foyer foyer 4
3.463659147869674
frail frail 4
3.4643304130162704
frame frame 4
3.465
frank frank 4
3.4656679151061174
fraud fraud 3
3.4650872817955114
freak freak 4
3.4657534246575343
freed freed 4
3.466417910447761
freer freer 4
3.467080745341615
fresh fresh 3
3.466501240694789
friar

inept inept 4
3.5033947623666344
inert inert 3
3.502906976744186
infer infer 3
3.5024201355275895
ingot ingot 3
3.501934235976789
inlay inlay 3
3.5014492753623188
inlet inlet 3
3.500965250965251
inner inner 4
3.501446480231437
input input 3
3.5009633911368017
inter inter 4
3.501443695861405
intro intro 3
3.5009615384615387
ionic ionic 3
3.500480307396734
irate irate 3
3.5
irony irony 4
3.5004793863854267
islet islet 2
3.4990421455938696
issue issue 4
3.4995215311004784
itchy itchy 4
3.5
ivory ivory 4
3.500477554918816
jaunt jaunt 4
3.5009541984732824
jazzy jazzy 4
3.501429933269781
jelly jelly 4
3.501904761904762
jerky jerky 4
3.5023786869647955
jetty jetty 3
3.5019011406844105
jewel jewel 4
3.5023741690408356
jiffy jiffy 4
3.5028462998102468
joint joint 3
3.5023696682464456
joist joist 4
3.502840909090909
joker joker 5
3.5042573320719015
jolly jolly 4
3.504725897920605
joust joust 4
3.50519357884797
judge judge 4
3.5056603773584905
juice juice 4
3.5061262959472197
juicy juicy 4
3.5065

navel navel 3
3.5050426687354537
needy needy 3
3.5046511627906978
neigh neigh 4
3.5050348567002323
nerdy nerdy 3
3.5046439628482973
nerve nerve 4
3.5050270688321734
never never 3
3.5046367851622873
newer newer 4
3.505019305019305
newly newly 4
3.505401234567901
nicer nicer 3
3.505011565150347
niche niche 4
3.505392912172573
niece niece 4
3.5057736720554273
night night 3
3.5053846153846155
ninja ninja 4
3.5057647963105305
ninny ninny 4
3.5061443932411676
ninth ninth 3
3.50575594781274
noble noble 3
3.5053680981595092
nobly nobly 4
3.5057471264367814
noise noise 3
3.5053598774885146
noisy noisy 3
3.504973221117062
nomad nomad 4
3.5053516819571864
noose noose 3
3.5049656226126813
north north 3
3.504580152671756
nosey nosey 3
3.50419527078566
notch notch 3
3.503810975609756
novel novel 4
3.5041888804265042
nudge nudge 3
3.503805175038052
nurse nurse 3
3.5034220532319393
nutty nutty 3
3.5030395136778116
nylon nylon 3
3.5026575550493546
nymph nymph 4
3.5030349013657056
oaken oaken 3
3.502653

In [ ]:

print('Guess: salet')
ts=input('Type Tiles:')

tgrid,plist_=reduce('salet',[int(ts[0]),int(ts[1]),int(ts[2]),int(ts[3]),int(ts[4])],big_arr,np.array(plist),np.array(glist))


while len(plist_)>3:

    x=prob_grid(tgrid)

    guess=glist[np.argmax(x)]
    
    print('')
    print('Possible Answers', len(plist_))
    print('Next Guess: ',guess)
    
    ts=input('Type Tiles:')

    tgrid,plist_=reduce(guess,[int(ts[0]),int(ts[1]),int(ts[2]),int(ts[3]),int(ts[4])],tgrid,plist_,np.array(glist))
    

print('Possible Answers', len(plist_))
print('Next Guess: ',plist_[0])
ts=input('Type Tiles:')

if [int(ts[0]),int(ts[1]),int(ts[2]),int(ts[3]),int(ts[4])]==[2,2,2,2,2]:
    
    print('Done')
    
        
else:
    tgrid,plist_=reduce(plist_[0],[int(ts[0]),int(ts[1]),int(ts[2]),int(ts[3]),int(ts[4])],tgrid,plist_,np.array(glist))
    
    print('Possible Answers', len(plist_))
    print('Next Guess: ',plist_[0])
    ts=input('Type Tiles:')
    if play.tiles(w,plist_[0])==[2,2,2,2,2]:
        
        print('Done')
        
            
        
    else:
        print('Answer: ',plist_[1])
            
     
        



Guess: salet
Type Tiles:00012

Possible Answers 22
Next Guess:  curio
Type Tiles:01000
Possible Answers 1
Next Guess:  debut


In [102]:
x=prob_grid(big_arr)

In [98]:
print(x[np.argmax(x)])
print(glist[np.argmax(x)])


5.885202744292758
soare


In [4]:
import numpy as np


big_arr=np.array(big_arr)

un_pat=np.unique(big_arr.reshape(big_arr.shape[0]**2,5),axis=0)


p=0
for i in range(len(un_pat)):
    p+=len(np.where(np.prod(big_arr == un_pat[i,:], axis = -1))[0])/(big_arr.shape[0])**2
print(p)

0.9999999999999991


In [24]:
play.tiles('homer','homer'

[2, 2, 2, 2, 2]

In [35]:
import numpy as np
ll=np.array([[6,5,4],[4,5,6],[4,5,6]])


print(np.where(np.prod(ll == [4,5,6], axis = -1)))



(array([1, 2]),)


In [ ]:
data = np.array( [  [1,2] , [1,3] ,[3,4], [1,2] , [0,9] ])

In [117]: np.where(np.prod(data == [1,2], axis = -1))
Out[117]: (array([0, 3]),)


False