In [1]:
from wbot import read,play
import numpy as np

plist=read.word_list('possible')
glist=read.word_list('allowed')


big_arr=[]

for i, g in enumerate(glist):
    small_arr=[]
    for j,p in enumerate(plist):
        small_arr+=[play.tiles(p,g)]
    
    big_arr+=[small_arr]
    
    if i%100==0:
        print(i)



big_arr=np.array(big_arr)

#np.save('tile_gird.npy',big_arr)

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900


In [232]:
print(big_arr.shape)
print(np.unique(big_arr[0,:,:],axis=0))

(12947, 2309, 5)
[[0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 2]
 [0 0 0 1 0]
 [0 0 0 1 1]
 [0 0 0 1 2]
 [0 0 0 2 0]
 [0 0 0 2 1]
 [0 0 0 2 2]
 [0 0 1 0 0]
 [0 0 1 0 1]
 [0 0 1 1 0]
 [0 0 1 1 1]
 [0 0 1 2 0]
 [0 0 1 2 1]
 [0 0 2 0 0]
 [0 0 2 0 1]
 [0 0 2 0 2]
 [0 0 2 1 0]
 [0 0 2 2 0]
 [0 0 2 2 1]
 [0 0 2 2 2]
 [0 1 0 0 0]
 [0 1 0 0 1]
 [0 1 0 0 2]
 [0 1 0 1 0]
 [0 1 0 1 1]
 [0 1 0 1 2]
 [0 1 0 2 0]
 [0 1 0 2 1]
 [0 1 0 2 2]
 [0 1 1 0 0]
 [0 1 1 0 1]
 [0 1 1 0 2]
 [0 1 1 1 0]
 [0 1 1 1 1]
 [0 1 1 1 2]
 [0 1 2 0 0]
 [0 1 2 1 0]
 [0 1 2 1 2]
 [0 1 2 2 0]
 [0 2 0 0 0]
 [0 2 0 0 1]
 [0 2 0 0 2]
 [0 2 0 1 0]
 [0 2 0 1 1]
 [0 2 0 2 0]
 [0 2 0 2 1]
 [0 2 0 2 2]
 [0 2 1 0 0]
 [0 2 1 0 1]
 [0 2 1 0 2]
 [0 2 1 1 0]
 [0 2 1 2 0]
 [0 2 1 2 1]
 [0 2 2 0 0]
 [0 2 2 0 1]
 [0 2 2 2 0]
 [1 0 0 0 0]
 [1 0 0 0 1]
 [1 0 0 0 2]
 [1 0 0 1 0]
 [1 0 0 1 1]
 [1 0 0 2 0]
 [1 0 0 2 1]
 [1 0 1 0 0]
 [1 1 0 0 0]
 [1 1 0 0 1]
 [1 1 0 0 2]
 [1 1 0 1 0]
 [1 1 0 1 1]
 [1 1 0 2 1]
 [1 2 0 0 0]
 [1 2 0 0 1]
 [1 2 0 2 0]
 [1 2 1 

In [2]:



def reduce(guess,tiles,tgrid,plist,glist):
    
    
    g_id=np.where(glist==guess)[0][0]

    w=np.where(np.prod(tgrid[g_id,:,:] == tiles, axis = -1))[0]
    
    return tgrid[:,w,:],plist[w]



def prob_grid(tgrid):
    
    gs,ps,_=tgrid.shape
    
    egrid=np.zeros(gs)
    
    for i in range(gs):
        
        un_pat=np.unique(tgrid[i,:,:],axis=0)
        #prob_row=np.zeros(ps)
        mean_inf=0
        
        for j in range(un_pat.shape[0]):
            
           
            p=len(np.where(np.prod(tgrid[i,:,:] == un_pat[j,:], axis = -1))[0])/ps
            mean_inf+=-p*np.log2(p)
            
            
            
        egrid[i]=mean_inf
    return egrid
            

    
        
    
    

In [ ]:
res=[]
for i,w in enumerate(plist):
    tgrid,plist_=reduce('salet',play.tiles(w,'salet'),big_arr,np.array(plist),np.array(glist))

    x=prob_grid(tgrid)

    guess=glist[np.argmax(x)]

    
    count=1

    while len(plist_)>3:
        
        count+=1

        tgrid,plist_=reduce(guess,play.tiles(w,guess),tgrid,plist_,np.array(glist))

        x=prob_grid(tgrid)

        guess=glist[np.argmax(x)]
        
    
    
    
    if play.tiles(w,plist_[0])==[2,2,2,2,2]:
        
        count+=1
        print(w,plist_[0],count)
        
    else:
        tgrid,plist_=reduce(plist_[0],play.tiles(w,plist_[0]),tgrid,plist_,np.array(glist))
        
        if play.tiles(w,plist_[0])==[2,2,2,2,2]:
            count+=2
            print(w,plist_[0],count)
            
        
        else:
            count+=3
            print(w,plist_[1],count)
            
     
        
    res+=[count]
    print(np.mean(res))
        

aback aback 3
3.0
abase abase 3
3.0
abate abate 3
3.0
abbey abbey 3
3.0
abbot abbot 3
3.0
abhor abhor 3
3.0
abide abide 3
3.0
abled abled 2
2.875
abode abode 4
3.0
abort abort 3
3.0
about about 3
3.0
above above 3
3.0
abuse abuse 3
3.0
abyss abyss 3
3.0
acorn acorn 3
3.0
acrid acrid 4
3.0625
actor actor 3
3.0588235294117645
acute acute 3
3.0555555555555554
adage adage 3
3.0526315789473686
adapt adapt 3
3.05
adept adept 3
3.0476190476190474
admin admin 3
3.0454545454545454
admit admit 4
3.0869565217391304
adobe adobe 4
3.125
adopt adopt 3
3.12
adore adore 3
3.1153846153846154
adorn adorn 3
3.111111111111111
adult adult 3
3.107142857142857
affix affix 4
3.1379310344827585
afire afire 3
3.1333333333333333
afoot afoot 4
3.161290322580645
afoul afoul 4
3.1875
after after 2
3.1515151515151514
again again 4
3.176470588235294
agape agape 4
3.2
agate agate 3
3.1944444444444446
agent agent 3
3.189189189189189
agile agile 3
3.1842105263157894
aging aging 3
3.1794871794871793
aglow aglow 3
3.175
a

bread bread 3
3.308550185873606
break break 3
3.3074074074074074
breed breed 4
3.309963099630996
briar briar 3
3.3088235294117645
bribe bribe 4
3.311355311355311
brick brick 3
3.31021897810219
bride bride 4
3.3127272727272725
brief brief 3
3.3115942028985508
brine brine 3
3.3104693140794224
bring bring 4
3.3129496402877696
brink brink 4
3.315412186379928
briny briny 4
3.317857142857143
brisk brisk 3
3.316725978647687
broad broad 3
3.3156028368794326
broil broil 4
3.3180212014134276
broke broke 4
3.3204225352112675
brood brood 4
3.3228070175438598
brook brook 4
3.325174825174825
broom broom 5
3.3310104529616726
broth broth 3
3.329861111111111
brown brown 4
3.332179930795848
brunt brunt 3
3.331034482758621
brush brush 3
3.329896907216495
brute brute 3
3.328767123287671
buddy buddy 4
3.3310580204778155
budge budge 4
3.3333333333333335
buggy buggy 4
3.335593220338983
bugle bugle 3
3.3344594594594597
build build 3
3.3333333333333335
built built 3
3.3322147651006713
bulge bulge 4
3.334448160

debit debit 4
3.385496183206107
debug debug 3
3.3847619047619046
debut debut 3
3.3840304182509504
decal decal 4
3.3851992409867173
decay decay 3
3.384469696969697
decor decor 3
3.383742911153119
decoy decoy 3
3.383018867924528
decry decry 3
3.3822975517890774
defer defer 3
3.3815789473684212
deign deign 3
3.3808630393996246
deity deity 3
3.3801498127340825
delay delay 3
3.3794392523364487
delta delta 2
3.376865671641791
delve delve 3
3.376163873370577
demon demon 3
3.37546468401487
demur demur 4
3.3766233766233764
denim denim 4
3.3777777777777778
dense dense 3
3.377079482439926
depot depot 3
3.376383763837638
depth depth 3
3.3756906077348066
derby derby 4
3.3768382352941178
deter deter 4
3.377981651376147
detox detox 3
3.3772893772893773
deuce deuce 3
3.376599634369287
devil devil 3
3.375912408759124
diary diary 3
3.3752276867030964
dicey dicey 3
3.3745454545454545
digit digit 3
3.3738656987295825
dilly dilly 3
3.3731884057971016
dimly dimly 3
3.37251356238698
diner diner 3
3.371841155

flush flush 3
3.3953786906290118
flute flute 3
3.394871794871795
flyer flyer 4
3.3956466069142124
foamy foamy 4
3.3964194373401533
focal focal 3
3.395913154533844
focus focus 3
3.395408163265306
foggy foggy 4
3.3961783439490447
foist foist 3
3.395674300254453
folio folio 3
3.3951715374841167
folly folly 4
3.3959390862944163
foray foray 3
3.3954372623574143
force force 4
3.3962025316455695
forge forge 4
3.3969658659924145
forgo forgo 4
3.397727272727273
forte forte 3
3.3972257250945774
forth forth 3
3.3967254408060454
forty forty 3
3.3962264150943398
forum forum 3
3.3957286432160805
found found 5
3.397741530740276
foyer foyer 4
3.398496240601504
frail frail 4
3.399249061326658
frame frame 4
3.4
frank frank 4
3.400749063670412
fraud fraud 3
3.4002493765586035
freak freak 4
3.4009962640099625
freed freed 4
3.4017412935323383
freer freer 4
3.4024844720496894
fresh fresh 3
3.401985111662531
friar friar 4
3.40272614622057
fried fried 4
3.4034653465346536
frill frill 4
3.404202719406675
frisk

inert inert 3
3.4467054263565893
infer infer 3
3.446272991287512
ingot ingot 3
3.4458413926499034
inlay inlay 3
3.4454106280193235
inlet inlet 3
3.444980694980695
inner inner 4
3.4455159112825458
input input 3
3.445086705202312
inter inter 4
3.445620789220404
intro intro 3
3.4451923076923077
ionic ionic 3
3.4447646493756006
irate irate 3
3.444337811900192
irony irony 4
3.444870565675935
islet islet 2
3.4434865900383143
issue issue 4
3.444019138755981
itchy itchy 4
3.4445506692160612
ivory ivory 4
3.445081184336199
jaunt jaunt 4
3.4456106870229006
jazzy jazzy 4
3.446139180171592
jelly jelly 4
3.4466666666666668
jerky jerky 4
3.4471931493815413
jetty jetty 3
3.446768060836502
jewel jewel 4
3.4472934472934473
jiffy jiffy 4
3.447817836812144
joint joint 3
3.44739336492891
joist joist 5
3.4488636363636362
joker joker 5
3.4503311258278146
jolly jolly 4
3.450850661625709
joust joust 4
3.4513692162417375
judge judge 4
3.45188679245283
juice juice 4
3.4524033930254476
juicy juicy 4
3.4529190207

In [287]:

print('Guess: salet')
ts=input('Type Tiles:')

tgrid,plist_=reduce('salet',[int(ts[0]),int(ts[1]),int(ts[2]),int(ts[3]),int(ts[4])],big_arr,np.array(plist),np.array(glist))


while len(plist_)>2:

    x=prob_grid(tgrid)

    guess=glist[np.argmax(x)]
    
    print('')
    print('Possible Answers', len(plist_))
    print('Next Guess: ',guess)
    
    ts=input('Type Tiles:')

    tgrid,plist_=reduce(guess,[int(ts[0]),int(ts[1]),int(ts[2]),int(ts[3]),int(ts[4])],tgrid,plist_,np.array(glist))
    



print('Answer:', plist_[0])



Guess: salet
Type Tiles:00010

Possible Answers 163
Next Guess:  drone
Type Tiles:11001

Possible Answers 2
Next Guess:  women
Type Tiles:20010
Answer: weird


In [102]:
x=prob_grid(big_arr)

In [98]:
print(x[np.argmax(x)])
print(glist[np.argmax(x)])


5.885202744292758
soare


In [4]:
import numpy as np


big_arr=np.array(big_arr)

un_pat=np.unique(big_arr.reshape(big_arr.shape[0]**2,5),axis=0)


p=0
for i in range(len(un_pat)):
    p+=len(np.where(np.prod(big_arr == un_pat[i,:], axis = -1))[0])/(big_arr.shape[0])**2
print(p)

0.9999999999999991


In [24]:
play.tiles('homer','homer'

[2, 2, 2, 2, 2]

In [35]:
import numpy as np
ll=np.array([[6,5,4],[4,5,6],[4,5,6]])


print(np.where(np.prod(ll == [4,5,6], axis = -1)))



(array([1, 2]),)


In [ ]:
data = np.array( [  [1,2] , [1,3] ,[3,4], [1,2] , [0,9] ])

In [117]: np.where(np.prod(data == [1,2], axis = -1))
Out[117]: (array([0, 3]),)


False