In [1]:
from wbot import read,play
import numpy as np

plist=read.word_list('possible')
glist=read.word_list('allowed')


big_arr=[]

for i, g in enumerate(glist):
    small_arr=[]
    for j,p in enumerate(plist):
        small_arr+=[play.tiles(p,g)]
    
    big_arr+=[small_arr]
    
    if i%100==0:
        print(i)



big_arr=np.array(big_arr)

#np.save('tile_gird.npy',big_arr)

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900


In [2]:



def reduce(guess,tiles,tgrid,plist,glist):
    
    
    g_id=np.where(glist==guess)[0][0]

    w=np.where(np.prod(tgrid[g_id,:,:] == tiles, axis = -1))[0]
    
    return tgrid[:,w,:],plist[w]



def prob_grid(tgrid):
    
    gs,ps,_=tgrid.shape
    
    egrid=np.zeros(gs)
    
    for i in range(gs):
        
        un_pat=np.unique(tgrid[i,:,:],axis=0)
        #prob_row=np.zeros(ps)
        mean_inf=0
        
        for j in range(un_pat.shape[0]):
            
           
            p=len(np.where(np.prod(tgrid[i,:,:] == un_pat[j,:], axis = -1))[0])/ps
            mean_inf+=-p*np.log2(p)
            
            
            
        egrid[i]=mean_inf
    return egrid

def cut_off(w,tgrid,plist,glist,igrid,count):
    ids=[]
    info_list=[]
    for p in plist:
        
        ids=np.where(glist==p)[0][0]
        
        info_list+=[igrid[ids]]
    
    guess=plist[np.argmax(info_list)]
    
    count+=1
    tiles=play.tiles(w,guess)
    if tiles==[2,2,2,2,2]:
        print(w,guess,count)
        return count        
    else:
        tgrid,plist_=reduce(guess,tiles,tgrid,plist,glist)
        
        if len(plist_)==1:
            count+=1
            print(w,plist_[0],count)
            return count
        else:
            return cut_off(w,tgrid,plist_,glist,igrid,count)
        
def manual_cut_off(tgrid,plist,glist,igrid):
    
    print('Possible Answers:', len(plist))
    ids=[]
    info_list=[]
    for p in plist:
        
        ids=np.where(glist==p)[0][0]
        
        info_list+=[igrid[ids]]
    
    guess=plist[np.argmax(info_list)]
    print('Guess:',guess)

    ts=input('Type Tiles')
    if [int(ts[0]),int(ts[1]),int(ts[2]),int(ts[3]),int(ts[4])]==[2,2,2,2,2]:
        print('Done')     
    else:
        tgrid,plist_=reduce(guess,[int(ts[0]),int(ts[1]),int(ts[2]),int(ts[3]),int(ts[4])],tgrid,plist,glist)
        if len(plist_)==1:
            print('Answer:', plist_[0])
        else:
            manual_cut_off(tgrid,plist_,glist,igrid)
                       

In [48]:
print(np.where(np.array(glist)=='salet'))

print(glist[12489])

(array([12489]),)
salet


In [49]:

un_pat=np.unique(big_arr[12489,:,:],axis=0)


g_word=[]
for pat in un_pat:
    
    print(pat)
    
    tgrid,plist_=reduce('salet',pat,big_arr,np.array(plist),np.array(glist))

    x=prob_grid(tgrid)

    guess=glist[np.argmax(x)]
    
    g_word+=[guess]
    
    print(pat,guess)
    

    

[0 0 0 0 0]
[0 0 0 0 0] cornu
[0 0 0 0 1]
[0 0 0 0 1] north
[0 0 0 0 2]
[0 0 0 0 2] groin
[0 0 0 1 0]
[0 0 0 1 0] drone
[0 0 0 1 1]
[0 0 0 1 1] trite
[0 0 0 1 2]
[0 0 0 1 2] curio
[0 0 0 2 0]
[0 0 0 2 0] nidor
[0 0 0 2 1]
[0 0 0 2 1] mohur
[0 0 0 2 2]
[0 0 0 2 2] cerne
[0 0 1 0 0]
[0 0 1 0 0] courd
[0 0 1 0 1]
[0 0 1 0 1] wroth
[0 0 1 0 2]
[0 0 1 0 2] bling
[0 0 1 1 0]
[0 0 1 1 0] beige
[0 0 1 1 1]
[0 0 1 1 1] shute
[0 0 1 1 2]
[0 0 1 1 2] swack
[0 0 1 2 0]
[0 0 1 2 0] livor
[0 0 1 2 1]
[0 0 1 2 1] women
[0 0 1 2 2]
[0 0 1 2 2] women
[0 0 2 0 0]
[0 0 2 0 0] doily
[0 0 2 0 1]
[0 0 2 0 1] nikau
[0 0 2 0 2]
[0 0 2 0 2] women
[0 0 2 1 0]
[0 0 2 1 0] himbo
[0 0 2 1 1]
[0 0 2 1 1] nikau
[0 0 2 2 0]
[0 0 2 2 0] mudge
[0 0 2 2 2]
[0 0 2 2 2] women
[0 1 0 0 0]
[0 1 0 0 0] brond
[0 1 0 0 1]
[0 1 0 0 1] tronc
[0 1 0 0 2]
[0 1 0 0 2] crudo
[0 1 0 1 0]
[0 1 0 1 0] beard
[0 1 0 1 1]
[0 1 0 1 1] grace
[0 1 0 1 2]
[0 1 0 1 2] crena
[0 1 0 2 0]
[0 1 0 2 0] unred
[0 1 0 2 1]
[0 1 0 2 1] women
[0 1 1 0 0

In [4]:
np.save('salet_patterns.npy',un_pat)
np.save('salet_guess.npy',g_word,)

NameError: name 'un_pat' is not defined

In [43]:
print(tgrid.shape)

(12947, 0, 5)


In [15]:
res=[]
sal_patterns=np.load('salet_patterns.npy')
sal_guess=np.load('salet_guess.npy')
for i,w in enumerate(plist):
    
    ts=play.tiles(w,'salet')
    
    tgrid,plist_=reduce('salet',ts,big_arr,np.array(plist),np.array(glist))

    guess=sal_guess[np.where(np.prod(sal_patterns ==ts, axis = -1))[0][0]]

    count=1

    while len(plist_)>6:
        
        count+=1

        tgrid,plist_=reduce(guess,play.tiles(w,guess),tgrid,plist_,np.array(glist))

        x=prob_grid(tgrid)

        guess=glist[np.argmax(x)]
        
    
    
    if count==1:
        x=prob_grid(tgrid)
        count=cut_off(w,tgrid,plist_,np.array(glist),x,count)  
    
    else:
        count=cut_off(w,tgrid,plist_,np.array(glist),x,count) 
    res+=[count]
    print(np.mean(res))
        

aback aback 3
3.0
abase abase 3
3.0
abate abate 3
3.0
abbey abbey 3
3.0
abbot abbot 3
3.0
abhor abhor 3
3.0
abide abide 3
3.0
abled abled 2
2.875
abode abode 4
3.0
abort abort 3
3.0
about about 3
3.0
above above 3
3.0
abuse abuse 3
3.0
abyss abyss 3
3.0
acorn acorn 3
3.0
acrid acrid 3
3.0
actor actor 3
3.0
acute acute 3
3.0
adage adage 3
3.0
adapt adapt 3
3.0
adept adept 3
3.0
admin admin 3
3.0
admit admit 4
3.0434782608695654
adobe adobe 4
3.0833333333333335
adopt adopt 3
3.08
adore adore 3
3.076923076923077
adorn adorn 3
3.074074074074074
adult adult 3
3.0714285714285716
affix affix 4
3.103448275862069
afire afire 3
3.1
afoot afoot 4
3.129032258064516
afoul afoul 3
3.125
after after 2
3.090909090909091
again again 4
3.1176470588235294
agape agape 4
3.142857142857143
agate agate 3
3.138888888888889
agent agent 3
3.135135135135135
agile agile 3
3.1315789473684212
aging aging 3
3.128205128205128
aglow aglow 3
3.125
agony agony 3
3.1219512195121952
agree agree 3
3.119047619047619
ahead a

briar briar 3
3.2573529411764706
bribe bribe 4
3.26007326007326
brick brick 3
3.259124087591241
bride bride 4
3.2618181818181817
brief brief 3
3.260869565217391
brine brine 3
3.259927797833935
bring bring 4
3.262589928057554
brink brink 4
3.2652329749103943
briny briny 4
3.267857142857143
brisk brisk 3
3.2669039145907472
broad broad 3
3.265957446808511
broil broil 4
3.2685512367491167
broke broke 4
3.2711267605633805
brood brood 4
3.2736842105263158
brook brook 4
3.2762237762237763
broom broom 5
3.2822299651567945
broth broth 3
3.28125
brown brown 4
3.283737024221453
brunt brunt 3
3.282758620689655
brush brush 3
3.281786941580756
brute brute 3
3.280821917808219
buddy buddy 4
3.2832764505119454
budge budge 4
3.2857142857142856
buggy buggy 4
3.288135593220339
bugle bugle 3
3.2871621621621623
build build 3
3.2861952861952863
built built 3
3.285234899328859
bulge bulge 4
3.2876254180602005
bulky bulky 3
3.2866666666666666
bully bully 3
3.2857142857142856
bunch bunch 3
3.2847682119205297
bu

decal decal 4
3.347248576850095
decay decay 3
3.346590909090909
decor decor 3
3.3459357277882797
decoy decoy 3
3.3452830188679243
decry decry 3
3.3446327683615817
defer defer 3
3.343984962406015
deign deign 3
3.3433395872420264
deity deity 3
3.342696629213483
delay delay 2
3.3401869158878505
delta delta 2
3.337686567164179
delve delve 3
3.3370577281191807
demon demon 3
3.336431226765799
demur demur 4
3.3376623376623376
denim denim 4
3.338888888888889
dense dense 3
3.3382624768946396
depot depot 3
3.337638376383764
depth depth 3
3.3370165745856353
derby derby 4
3.338235294117647
deter deter 3
3.3376146788990826
detox detox 3
3.336996336996337
deuce deuce 3
3.3363802559414992
devil devil 3
3.335766423357664
diary diary 3
3.3351548269581057
dicey dicey 3
3.3345454545454545
digit digit 3
3.3339382940108893
dilly dilly 3
3.3333333333333335
dimly dimly 3
3.332730560578662
diner diner 3
3.332129963898917
dingo dingo 4
3.3333333333333335
dingy dingy 4
3.3345323741007196
diode diode 3
3.3339317

flute flute 3
3.3564102564102565
flyer flyer 5
3.358514724711908
foamy foamy 4
3.3593350383631715
focal focal 3
3.3588761174968074
focus focus 3
3.358418367346939
foggy foggy 4
3.359235668789809
foist foist 3
3.3587786259541983
folio folio 3
3.3583227445997457
folly folly 3
3.3578680203045685
foray foray 3
3.3574144486692017
force force 4
3.358227848101266
forge forge 4
3.359039190897598
forgo forgo 4
3.359848484848485
forte forte 3
3.359394703656999
forth forth 3
3.358942065491184
forty forty 3
3.358490566037736
forum forum 3
3.358040201005025
found found 5
3.3601003764115434
foyer foyer 4
3.3609022556390977
frail frail 4
3.3617021276595747
frame frame 4
3.3625
frank frank 4
3.363295880149813
fraud fraud 3
3.36284289276808
freak freak 4
3.3636363636363638
freed freed 5
3.3656716417910446
freer freer 4
3.3664596273291925
fresh fresh 3
3.366004962779156
friar friar 4
3.3667905824039654
fried fried 5
3.368811881188119
frill frill 3
3.3683559950556243
frisk frisk 4
3.369135802469136
fritz

inlay inlay 3
3.4154589371980677
inlet inlet 3
3.4150579150579152
inner inner 4
3.415621986499518
input input 3
3.4152215799614645
inter inter 4
3.4157844080846966
intro intro 3
3.4153846153846152
ionic ionic 3
3.414985590778098
irate irate 3
3.4145873320537428
irony irony 5
3.4161073825503356
islet islet 2
3.414750957854406
issue issue 4
3.415311004784689
itchy itchy 4
3.415869980879541
ivory ivory 4
3.416427889207259
jaunt jaunt 4
3.4169847328244276
jazzy jazzy 4
3.417540514775977
jelly jelly 4
3.4180952380952383
jerky jerky 4
3.4186489058039964
jetty jetty 3
3.418250950570342
jewel jewel 4
3.4188034188034186
jiffy jiffy 4
3.4193548387096775
joint joint 3
3.418957345971564
joist joist 5
3.4204545454545454
joker joker 5
3.421948912015137
jolly jolly 6
3.4243856332703215
joust joust 4
3.424929178470255
judge judge 4
3.4254716981132076
juice juice 4
3.4260131950989634
juicy juicy 4
3.426553672316384
jumbo jumbo 4
3.4270931326434617
jumpy jumpy 5
3.4285714285714284
junta junta 4
3.429107

naval naval 3
3.436335403726708
navel navel 3
3.4359968968192396
needy needy 3
3.4356589147286822
neigh neigh 4
3.436096049573974
nerdy nerdy 3
3.4357585139318885
nerve nerve 4
3.4361948955916475
never never 3
3.435857805255023
newer newer 4
3.436293436293436
newly newly 4
3.4367283950617282
nicer nicer 3
3.4363916730917503
niche niche 4
3.436825885978428
niece niece 4
3.4372594303310238
night night 3
3.436923076923077
ninja ninja 4
3.4373558800922366
ninny ninny 4
3.4377880184331797
ninth ninth 3
3.4374520337682273
noble noble 3
3.437116564417178
nobly nobly 4
3.4375478927203065
noise noise 3
3.4372128637059722
noisy noisy 3
3.4368783473603672
nomad nomad 4
3.437308868501529
noose noose 3
3.436974789915966
north north 3
3.4366412213740456
nosey nosey 3
3.4363081617086193
notch notch 3
3.4359756097560976
novel novel 4
3.4364051789794363
nudge nudge 3
3.4360730593607305
nurse nurse 3
3.4357414448669203
nutty nutty 3
3.435410334346505
nylon nylon 3
3.4350797266514808
nymph nymph 4
3.4355

rarer rarer 4
3.4714285714285715
raspy raspy 3
3.4711226476314083
ratio ratio 3
3.470817120622568
ratty ratty 3
3.4705119896305896
raven raven 5
3.471502590673575
rayon rayon 3
3.4711974110032364
razor razor 5
3.4721862871927556
reach reach 3
3.4718810601163543
react react 3
3.4715762273901807
ready ready 3
3.471271788250484
realm realm 3
3.470967741935484
rearm rearm 4
3.4713088330109607
rebar rebar 3
3.471005154639175
rebel rebel 4
3.471345782356729
rebus rebus 3
3.471042471042471
rebut rebut 4
3.4713826366559486
recap recap 3
3.4710796915167097
recur recur 4
3.4714193962748876
recut recut 3
3.4711168164313224
reedy reedy 3
3.4708146247594613
refer refer 4
3.4711538461538463
refit refit 3
3.4708520179372195
regal regal 3
3.470550576184379
rehab rehab 4
3.470889315419066
reign reign 3
3.4705882352941178
relax relax 3
3.4702875399361024
relay relay 3
3.469987228607918
relic relic 3
3.469687300574346
remit remit 4
3.470025510204082
renal renal 4
3.470363288718929
renew renew 4
3.4707006

slurp slurp 4
3.4511991076408255
slush slush 4
3.451505016722408
slyly slyly 4
3.4518105849582175
smack smack 3
3.4515590200445434
small small 3
3.451307735114079
smart smart 2
3.4505005561735262
smash smash 3
3.4502501389660925
smear smear 3
3.45
smell smell 3
3.4497501388117713
smelt smelt 3
3.4495005549389566
smile smile 3
3.449251247920133
smirk smirk 4
3.449556541019956
smite smite 3
3.4493074792243767
smith smith 4
3.449612403100775
smock smock 4
3.449916989485335
smoke smoke 3
3.4496681415929205
smoky smoky 4
3.4499723604201216
smote smote 3
3.4497237569060775
snack snack 4
3.45002760905577
snail snail 3
3.4497792494481234
snake snake 3
3.449531163816878
snaky snaky 4
3.449834619625138
snare snare 4
3.450137741046832
snarl snarl 3
3.4498898678414096
sneak sneak 4
3.4501926252063844
sneer sneer 3
3.44994499449945
snide snide 3
3.4496976360637714
sniff sniff 3
3.4494505494505496
snipe snipe 3
3.4492037342119715
snoop snoop 3
3.4489571899012073
snore snore 3
3.4487109160724083
snor

thorn thorn 3
3.429130009775171
those those 3
3.4289203712750367
three three 3
3.4287109375
threw threw 4
3.4289897510980967
throb throb 3
3.428780487804878
throw throw 4
3.4290589956118964
thrum thrum 3
3.4288499025341133
thumb thumb 4
3.429128105211885
thump thump 4
3.4294060370009736
thyme thyme 4
3.429683698296837
tiara tiara 3
3.429474708171206
tibia tibia 3
3.429265921244531
tidal tidal 3
3.4290573372206024
tiger tiger 4
3.429334628460418
tight tight 5
3.4300970873786407
tilde tilde 2
3.4294032023289667
timer timer 3
3.4291949563530553
timid timid 3
3.4289869122636936
tipsy tipsy 3
3.428779069767442
titan titan 3
3.4285714285714284
tithe tithe 3
3.4283639883833494
title title 3
3.4281567489114657
toast toast 3
3.4279497098646035
today today 3
3.4277428709521507
toddy toddy 4
3.4280193236714975
token token 3
3.4278126508932885
tonal tonal 3
3.4276061776061777
tonga tonga 3
3.4273999035214664
tonic tonic 3
3.4271938283510126
tooth tooth 4
3.4274698795180725
topaz topaz 4
3.42774566

wrote wrote 4
3.449521322889469
wrung wrung 4
3.449760765550239
wryly wryly 4
3.45
yacht yacht 3
3.4498044328552804
yearn yearn 4
3.4500434404865334
yeast yeast 4
3.4502822405557967
yield yield 5
3.450954861111111
young young 4
3.4511930585683297
youth youth 5
3.4518647007805723
zebra zebra 3
3.451668833983528
zesty zesty 3
3.451473136915078
zonal zonal 3
3.451277609354699


In [3]:
# print('Guess: salet')
ts=input('Type Tiles:')

tgrid,plist_=reduce('salet',[int(ts[0]),int(ts[1]),int(ts[2]),int(ts[3]),int(ts[4])],big_arr,np.array(plist),np.array(glist))

x=prob_grid(tgrid)

guess=glist[np.argmax(x)]

while len(plist_)>5:
    
    print('')
    print('Possible Answers', len(plist_))
    print('Next Guess: ',guess)
    
    ts=input('Type Tiles:')

    tgrid,plist_=reduce(guess,[int(ts[0]),int(ts[1]),int(ts[2]),int(ts[3]),int(ts[4])],tgrid,plist_,np.array(glist))
    
    x=prob_grid(tgrid)

    guess=glist[np.argmax(x)]


    
    
count=manual_cut_off(tgrid,plist_,np.array(glist),x)   



Type Tiles:01000

Possible Answers 101
Next Guess:  brond
Type Tiles:00010

Possible Answers 6
Next Guess:  cabin
Type Tiles:01002
Possible Answers: 1
Guess: human


KeyboardInterrupt: Interrupted by user

In [102]:
x=prob_grid(big_arr)

In [98]:
print(x[np.argmax(x)])
print(glist[np.argmax(x)])


5.885202744292758
soare


In [4]:
import numpy as np


big_arr=np.array(big_arr)

un_pat=np.unique(big_arr.reshape(big_arr.shape[0]**2,5),axis=0)


p=0
for i in range(len(un_pat)):
    p+=len(np.where(np.prod(big_arr == un_pat[i,:], axis = -1))[0])/(big_arr.shape[0])**2
print(p)

0.9999999999999991


In [24]:
play.tiles('homer','homer'

[2, 2, 2, 2, 2]

In [35]:
import numpy as np
ll=np.array([[6,5,4],[4,5,6],[4,5,6]])


print(np.where(np.prod(ll == [4,5,6], axis = -1)))



(array([1, 2]),)


In [ ]:
data = np.array( [  [1,2] , [1,3] ,[3,4], [1,2] , [0,9] ])

In [117]: np.where(np.prod(data == [1,2], axis = -1))
Out[117]: (array([0, 3]),)


False