In [1]:
from wbot import read,play
import numpy as np

plist=read.word_list('possible')
glist=read.word_list('allowed')


big_arr=[]

for i, g in enumerate(glist):
    small_arr=[]
    for j,p in enumerate(plist):
        small_arr+=[play.tiles(p,g)]
    
    big_arr+=[small_arr]
    
    if i%100==0:
        print(i)



big_arr=np.array(big_arr)

#np.save('tile_gird.npy',big_arr)

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900


In [2]:
def reduce(guess,tiles,tgrid,plist,glist):
    
    
    g_id=np.where(glist==guess)[0][0]

    w=np.where(np.prod(tgrid[g_id,:,:] == tiles, axis = -1))[0]
    
    return tgrid[:,w,:],plist[w]



def prob_grid(tgrid):
    
    gs,ps,_=tgrid.shape
    
    egrid=np.zeros(gs)
    
    for i in range(gs):
        
        un_pat=np.unique(tgrid[i,:,:],axis=0)
        mean_inf=0
        
        for j in range(un_pat.shape[0]):
            
           
            p=len(np.where(np.prod(tgrid[i,:,:] == un_pat[j,:], axis = -1))[0])/ps
            mean_inf+=-p*np.log2(p)

        egrid[i]=mean_inf
    return egrid

def cut_off(w,tgrid,plist,glist,igrid,count):
    ids=[]
    info_list=[]
    for p in plist:
        
        ids=np.where(glist==p)[0][0]
        
        info_list+=[igrid[ids]]
    
    guess=plist[np.argmax(info_list)]
    
    count+=1
    tiles=play.tiles(w,guess)
    if tiles==[2,2,2,2,2]:
        print(w,guess,count)
        return count        
    else:
        tgrid,plist_=reduce(guess,tiles,tgrid,plist,glist)
        
        if len(plist_)==1:
            count+=1
            print(w,plist_[0],count)
            return count
        else:
            return cut_off(w,tgrid,plist_,glist,igrid,count)
        
def manual_cut_off(tgrid,plist,glist,igrid):
    
    print('Possible Answers:', len(plist))
    ids=[]
    info_list=[]
    for p in plist:
        
        ids=np.where(glist==p)[0][0]
        
        info_list+=[igrid[ids]]
    
    guess=plist[np.argmax(info_list)]
    print('Guess:',guess)

    ts=input('Type Tiles')
    if [int(ts[0]),int(ts[1]),int(ts[2]),int(ts[3]),int(ts[4])]==[2,2,2,2,2]:
        print('Done')     
    else:
        tgrid,plist_=reduce(guess,[int(ts[0]),int(ts[1]),int(ts[2]),int(ts[3]),int(ts[4])],tgrid,plist,glist)
        if len(plist_)==1:
            print('Answer:', plist_[0])
        else:
            manual_cut_off(tgrid,plist_,glist,igrid)
                       

In [48]:
print(np.where(np.array(glist)=='salet'))

print(glist[12489])

(array([12489]),)
salet


In [49]:

un_pat=np.unique(big_arr[12489,:,:],axis=0)


g_word=[]
for pat in un_pat:
    
    print(pat)
    
    tgrid,plist_=reduce('salet',pat,big_arr,np.array(plist),np.array(glist))

    x=prob_grid(tgrid)

    guess=glist[np.argmax(x)]
    
    g_word+=[guess]
    
    print(pat,guess)
    

    

[0 0 0 0 0]
[0 0 0 0 0] cornu
[0 0 0 0 1]
[0 0 0 0 1] north
[0 0 0 0 2]
[0 0 0 0 2] groin
[0 0 0 1 0]
[0 0 0 1 0] drone
[0 0 0 1 1]
[0 0 0 1 1] trite
[0 0 0 1 2]
[0 0 0 1 2] curio
[0 0 0 2 0]
[0 0 0 2 0] nidor
[0 0 0 2 1]
[0 0 0 2 1] mohur
[0 0 0 2 2]
[0 0 0 2 2] cerne
[0 0 1 0 0]
[0 0 1 0 0] courd
[0 0 1 0 1]
[0 0 1 0 1] wroth
[0 0 1 0 2]
[0 0 1 0 2] bling
[0 0 1 1 0]
[0 0 1 1 0] beige
[0 0 1 1 1]
[0 0 1 1 1] shute
[0 0 1 1 2]
[0 0 1 1 2] swack
[0 0 1 2 0]
[0 0 1 2 0] livor
[0 0 1 2 1]
[0 0 1 2 1] women
[0 0 1 2 2]
[0 0 1 2 2] women
[0 0 2 0 0]
[0 0 2 0 0] doily
[0 0 2 0 1]
[0 0 2 0 1] nikau
[0 0 2 0 2]
[0 0 2 0 2] women
[0 0 2 1 0]
[0 0 2 1 0] himbo
[0 0 2 1 1]
[0 0 2 1 1] nikau
[0 0 2 2 0]
[0 0 2 2 0] mudge
[0 0 2 2 2]
[0 0 2 2 2] women
[0 1 0 0 0]
[0 1 0 0 0] brond
[0 1 0 0 1]
[0 1 0 0 1] tronc
[0 1 0 0 2]
[0 1 0 0 2] crudo
[0 1 0 1 0]
[0 1 0 1 0] beard
[0 1 0 1 1]
[0 1 0 1 1] grace
[0 1 0 1 2]
[0 1 0 1 2] crena
[0 1 0 2 0]
[0 1 0 2 0] unred
[0 1 0 2 1]
[0 1 0 2 1] women
[0 1 1 0 0

In [4]:
np.save('salet_patterns.npy',un_pat)
np.save('salet_guess.npy',g_word,)

NameError: name 'un_pat' is not defined

In [43]:
print(tgrid.shape)

(12947, 0, 5)


In [ ]:
res=[]
sal_patterns=np.load('salet_patterns.npy')
sal_guess=np.load('salet_guess.npy')
for i,w in enumerate(plist):
    
    ts=play.tiles(w,'salet')
    
    tgrid,plist_=reduce('salet',ts,big_arr,np.array(plist),np.array(glist))

    guess=sal_guess[np.where(np.prod(sal_patterns ==ts, axis = -1))[0][0]]

    count=1

    while len(plist_)>6:
        
        count+=1

        tgrid,plist_=reduce(guess,play.tiles(w,guess),tgrid,plist_,np.array(glist))

        x=prob_grid(tgrid)

        guess=glist[np.argmax(x)]
        
    
    
    if count==1:
        x=prob_grid(tgrid)
        count=cut_off(w,tgrid,plist_,np.array(glist),x,count)  
    
    else:
        count=cut_off(w,tgrid,plist_,np.array(glist),x,count) 
    res+=[count]
    print(np.mean(res))
        

aback aback 3
3.0
abase abase 3
3.0
abate abate 3
3.0
abbey abbey 3
3.0
abbot abbot 3
3.0
abhor abhor 3
3.0
abide abide 3
3.0
abled abled 2
2.875
abode abode 4
3.0
abort abort 3
3.0
about about 3
3.0
above above 3
3.0
abuse abuse 3
3.0
abyss abyss 3
3.0
acorn acorn 3
3.0
acrid acrid 3
3.0
actor actor 3
3.0
acute acute 3
3.0
adage adage 3
3.0
adapt adapt 3
3.0
adept adept 3
3.0
admin admin 3
3.0
admit admit 4
3.0434782608695654
adobe adobe 4
3.0833333333333335
adopt adopt 3
3.08
adore adore 3
3.076923076923077
adorn adorn 3
3.074074074074074
adult adult 3
3.0714285714285716
affix affix 4
3.103448275862069
afire afire 3
3.1
afoot afoot 4
3.129032258064516
afoul afoul 3
3.125
after after 2
3.090909090909091
again again 3
3.088235294117647
agape agape 4
3.1142857142857143
agate agate 3
3.111111111111111
agent agent 3
3.108108108108108
agile agile 3
3.1052631578947367
aging aging 3
3.1025641025641026
aglow aglow 3
3.1
agony agony 3
3.097560975609756
agree agree 3
3.0952380952380953
ahead ah

break break 3
3.240740740740741
breed breed 3
3.2398523985239853
briar briar 3
3.238970588235294
bribe bribe 4
3.241758241758242
brick brick 3
3.240875912408759
bride bride 4
3.2436363636363637
brief brief 3
3.2427536231884058
brine brine 3
3.2418772563176894
bring bring 3
3.241007194244604
brink brink 4
3.2437275985663083
briny briny 5
3.25
brisk brisk 3
3.2491103202846974
broad broad 3
3.24822695035461
broil broil 4
3.2508833922261484
broke broke 4
3.2535211267605635
brood brood 4
3.256140350877193
brook brook 4
3.2587412587412588
broom broom 5
3.264808362369338
broth broth 3
3.263888888888889
brown brown 3
3.262975778546713
brunt brunt 3
3.2620689655172415
brush brush 3
3.261168384879725
brute brute 3
3.26027397260274
buddy buddy 4
3.262798634812287
budge budge 4
3.2653061224489797
buggy buggy 4
3.2677966101694915
bugle bugle 3
3.266891891891892
build build 3
3.265993265993266
built built 3
3.2651006711409396
bulge bulge 4
3.2675585284280935
bulky bulky 3
3.2666666666666666
bully bu

debug debug 3
3.335238095238095
debut debut 3
3.334600760456274
decal decal 4
3.3358633776091082
decay decay 3
3.335227272727273
decor decor 3
3.334593572778828
decoy decoy 3
3.3339622641509434
decry decry 3
3.3333333333333335
defer defer 3
3.332706766917293
deign deign 3
3.3320825515947465
deity deity 3
3.331460674157303
delay delay 2
3.3289719626168224
delta delta 2
3.326492537313433
delve delve 3
3.3258845437616387
demon demon 3
3.325278810408922
demur demur 4
3.326530612244898
denim denim 4
3.327777777777778
dense dense 3
3.3271719038817005
depot depot 3
3.3265682656826567
depth depth 3
3.3259668508287294
derby derby 4
3.327205882352941
deter deter 3
3.326605504587156
detox detox 3
3.326007326007326
deuce deuce 3
3.3254113345521024
devil devil 3
3.3248175182481754
diary diary 3
3.324225865209472
dicey dicey 3
3.3236363636363637
digit digit 3
3.323049001814882
dilly dilly 3
3.322463768115942
dimly dimly 3
3.321880650994575
diner diner 3
3.32129963898917
dingo dingo 4
3.3225225225225

flunk flunk 4
3.347043701799486
flush flush 3
3.3465982028241337
flute flute 3
3.3461538461538463
flyer flyer 5
3.348271446862996
foamy foamy 4
3.3491048593350383
focal focal 3
3.3486590038314175
focus focus 3
3.3482142857142856
foggy foggy 4
3.349044585987261
foist foist 3
3.3486005089058524
folio folio 3
3.3481575603557814
folly folly 3
3.3477157360406093
foray foray 3
3.347275031685678
force force 4
3.348101265822785
forge forge 3
3.347661188369153
forgo forgo 4
3.3484848484848486
forte forte 3
3.348045397225725
forth forth 3
3.347607052896725
forty forty 3
3.3471698113207546
forum forum 3
3.3467336683417086
found found 5
3.3488080301129233
foyer foyer 4
3.3496240601503757
frail frail 4
3.3504380475594493
frame frame 4
3.35125
frank frank 4
3.352059925093633
fraud fraud 3
3.3516209476309227
freak freak 3
3.3511830635118307
freed freed 5
3.353233830845771
freer freer 4
3.3540372670807455
fresh fresh 3
3.3535980148883375
friar friar 4
3.354399008674102
fried fried 5
3.3564356435643563

inept inept 4
3.4102812803103784
inert inert 3
3.4098837209302326
infer infer 3
3.409486931268151
ingot ingot 3
3.409090909090909
inlay inlay 3
3.408695652173913
inlet inlet 3
3.408301158301158
inner inner 4
3.4088717454194795
input input 3
3.4084778420038537
inter inter 4
3.4090471607314727
intro intro 3
3.4086538461538463
ionic ionic 3
3.4082612872238234
irate irate 3
3.407869481765835
irony irony 5
3.4093959731543624
islet islet 2
3.4080459770114944
issue issue 4
3.4086124401913875
itchy itchy 4
3.4091778202676863
ivory ivory 4
3.4097421203438394
jaunt jaunt 4
3.4103053435114505
jazzy jazzy 4
3.4108674928503335
jelly jelly 4
3.4114285714285715
jerky jerky 4
3.411988582302569
jetty jetty 3
3.411596958174905
jewel jewel 4
3.4121557454890787
jiffy jiffy 4
3.4127134724857684
joint joint 3
3.4123222748815167
joist joist 5
3.413825757575758
joker joker 5
3.415326395458846
jolly jolly 6
3.4177693761814747
joust joust 4
3.4183191690273844
judge judge 4
3.418867924528302
juice juice 4
3.4194

In [3]:
# print('Guess: salet')
ts=input('Type Tiles:')

tgrid,plist_=reduce('salet',[int(ts[0]),int(ts[1]),int(ts[2]),int(ts[3]),int(ts[4])],big_arr,np.array(plist),np.array(glist))

x=prob_grid(tgrid)

guess=glist[np.argmax(x)]

while len(plist_)>5:
    
    print('')
    print('Possible Answers', len(plist_))
    print('Next Guess: ',guess)
    
    ts=input('Type Tiles:')

    tgrid,plist_=reduce(guess,[int(ts[0]),int(ts[1]),int(ts[2]),int(ts[3]),int(ts[4])],tgrid,plist_,np.array(glist))
    
    x=prob_grid(tgrid)

    guess=glist[np.argmax(x)]


    
    
count=manual_cut_off(tgrid,plist_,np.array(glist),x)   



Type Tiles:01000

Possible Answers 101
Next Guess:  brond
Type Tiles:00010

Possible Answers 6
Next Guess:  cabin
Type Tiles:01002
Possible Answers: 1
Guess: human


KeyboardInterrupt: Interrupted by user

In [102]:
x=prob_grid(big_arr)

In [98]:
print(x[np.argmax(x)])
print(glist[np.argmax(x)])


5.885202744292758
soare


In [4]:
import numpy as np


big_arr=np.array(big_arr)

un_pat=np.unique(big_arr.reshape(big_arr.shape[0]**2,5),axis=0)


p=0
for i in range(len(un_pat)):
    p+=len(np.where(np.prod(big_arr == un_pat[i,:], axis = -1))[0])/(big_arr.shape[0])**2
print(p)

0.9999999999999991


In [24]:
play.tiles('homer','homer'

[2, 2, 2, 2, 2]

In [35]:
import numpy as np
ll=np.array([[6,5,4],[4,5,6],[4,5,6]])


print(np.where(np.prod(ll == [4,5,6], axis = -1)))



(array([1, 2]),)


In [ ]:
data = np.array( [  [1,2] , [1,3] ,[3,4], [1,2] , [0,9] ])

In [117]: np.where(np.prod(data == [1,2], axis = -1))
Out[117]: (array([0, 3]),)


False