In [202]:
from wbot import read,play
import numpy as np

plist=read.word_list('possible')
glist=read.word_list('allowed')


big_arr=[]

for i, g in enumerate(glist):
    small_arr=[]
    for j,p in enumerate(plist):
        small_arr+=[play.tiles(p,g)]
    
    big_arr+=[small_arr]
    
    if i%100==0:
        print(i)



big_arr=np.array(big_arr)

np.save('tile_gird.npy',big_arr)

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900


In [158]:
print(big_arr.shape)
print(np.unique(big_arr[0,:,:],axis=0))

(2309, 2309, 5)
[[0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 2]
 [0 0 0 1 0]
 [0 0 0 1 1]
 [0 0 0 1 2]
 [0 0 0 2 0]
 [0 0 0 2 2]
 [0 0 2 0 0]
 [0 0 2 0 1]
 [0 0 2 0 2]
 [0 0 2 1 0]
 [0 0 2 1 2]
 [0 0 2 2 0]
 [0 0 2 2 2]
 [0 1 0 0 0]
 [0 1 0 0 1]
 [0 1 0 0 2]
 [0 1 0 1 0]
 [0 1 0 2 0]
 [0 1 0 2 2]
 [0 1 2 0 0]
 [0 1 2 0 1]
 [0 1 2 0 2]
 [0 1 2 2 0]
 [0 1 2 2 2]
 [0 2 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 1]
 [1 0 0 0 2]
 [1 0 0 1 0]
 [1 0 0 1 1]
 [1 0 0 1 2]
 [1 0 0 2 0]
 [1 0 1 0 0]
 [1 0 1 0 1]
 [1 0 1 0 2]
 [1 0 1 1 0]
 [1 0 2 0 0]
 [1 0 2 0 1]
 [1 1 0 0 0]
 [1 1 0 0 1]
 [1 1 0 0 2]
 [1 1 0 1 0]
 [1 1 0 2 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [2 0 0 0 0]
 [2 0 0 0 1]
 [2 0 0 1 0]
 [2 0 1 0 0]
 [2 0 2 0 0]
 [2 0 2 0 1]
 [2 1 0 0 0]
 [2 2 0 0 0]
 [2 2 2 0 0]
 [2 2 2 2 2]]


In [218]:



def reduce(guess,tiles,tgrid,plist,glist):
    
    
    g_id=np.where(glist==guess)[0][0]

    w=np.where(np.prod(tgrid[g_id,:,:] == tiles, axis = -1))[0]
    
    return tgrid[:,w,:],plist[w]



def prob_grid(tgrid):
    
    gs,ps,_=tgrid.shape
    
    egrid=np.zeros(gs)
    
    for i in range(gs):
        
        un_pat=np.unique(tgrid[i,:,:],axis=0)
        #prob_row=np.zeros(ps)
        mean_inf=0
        for j in range(un_pat.shape[0]):
            p=len(np.where(np.prod(tgrid[i,:,:] == un_pat[j,:], axis = -1))[0])/ps
            mean_inf+=-p*np.log2(p)
        egrid[i]=mean_inf
    return egrid
            

    
        
    
    

In [222]:
%%timeit

w='loyal'




tgrid,plist_=reduce('salet',play.tiles(w,'salet'),big_arr,np.array(plist),np.array(glist))

x=prob_grid(tgrid)

guess=glist[np.argmax(x)]

print(guess)

print(plist_)


while len(plist_)>1:

    tgrid,plist_=reduce(guess,play.tiles(w,guess),tgrid,plist_,np.array(glist))

    x=prob_grid(tgrid)

    guess=glist[np.argmax(x)]

    print(guess)

    print(plist_)




corni
['afoul' 'alarm' 'album' 'alibi' 'align' 'along' 'aloof' 'aloud' 'alpha'
 'amply' 'annul' 'anvil' 'apply' 'avail' 'awful' 'axial' 'black' 'bland'
 'blank' 'brawl' 'chalk' 'clack' 'claim' 'clamp' 'clang' 'clank' 'cloak'
 'coral' 'crawl' 'drawl' 'final' 'flack' 'flail' 'flair' 'flaky' 'flank'
 'flora' 'focal' 'frail' 'gland' 'grail' 'iliac' 'koala' 'llama' 'loamy'
 'local' 'loyal' 'lunar' 'modal' 'moral' 'mural' 'offal' 'plaid' 'plain'
 'plank' 'plaza' 'quail' 'qualm' 'rival' 'royal' 'rural' 'viola' 'viral'
 'vocal' 'voila' 'zonal']
soman
['koala' 'loamy' 'loyal' 'modal']
women
['loyal']
corni
['afoul' 'alarm' 'album' 'alibi' 'align' 'along' 'aloof' 'aloud' 'alpha'
 'amply' 'annul' 'anvil' 'apply' 'avail' 'awful' 'axial' 'black' 'bland'
 'blank' 'brawl' 'chalk' 'clack' 'claim' 'clamp' 'clang' 'clank' 'cloak'
 'coral' 'crawl' 'drawl' 'final' 'flack' 'flail' 'flair' 'flaky' 'flank'
 'flora' 'focal' 'frail' 'gland' 'grail' 'iliac' 'koala' 'llama' 'loamy'
 'local' 'loyal' 'lunar' 'moda

In [ ]:
res=[]
for i,w in enumerate(plist):
    tgrid,plist_=reduce('salet',play.tiles(w,'salet'),big_arr,np.array(plist),np.array(glist))

    x=prob_grid(tgrid)

    guess=glist[np.argmax(x)]

    
    count=1

    while len(plist_)>1:
        
        count+=1

        tgrid,plist_=reduce(guess,play.tiles(w,guess),tgrid,plist_,np.array(glist))

        x=prob_grid(tgrid)

        guess=glist[np.argmax(x)]

    count+=1
    print(w,plist_)
    
    res+=[count]
    print(np.mean(res))
        
        
    

aback ['aback']
3.0
abase ['abase']
3.0
abate ['abate']
3.3333333333333335
abbey ['abbey']
3.25
abbot ['abbot']
3.4
abhor ['abhor']
3.5
abide ['abide']
3.5714285714285716
abled ['abled']
3.5
abode ['abode']
3.5555555555555554
abort ['abort']
3.5
about ['about']
3.4545454545454546
above ['above']
3.4166666666666665
abuse ['abuse']
3.3846153846153846
abyss ['abyss']
3.4285714285714284
acorn ['acorn']
3.4
acrid ['acrid']
3.4375
actor ['actor']
3.411764705882353
acute ['acute']
3.388888888888889
adage ['adage']
3.4210526315789473
adapt ['adapt']
3.45
adept ['adept']
3.4761904761904763
admin ['admin']
3.4545454545454546
admit ['admit']
3.4782608695652173
adobe ['adobe']
3.5
adopt ['adopt']
3.48
adore ['adore']
3.4615384615384617
adorn ['adorn']
3.4444444444444446
adult ['adult']
3.4285714285714284
affix ['affix']
3.4482758620689653
afire ['afire']
3.466666666666667
afoot ['afoot']
3.4838709677419355
afoul ['afoul']
3.5
after ['after']
3.4545454545454546
again ['again']
3.4705882352941178
ag

borne ['borne']
3.502008032128514
bosom ['bosom']
3.5
bossy ['bossy']
3.50199203187251
botch ['botch']
3.503968253968254
bough ['bough']
3.505928853754941
boule ['boule']
3.5078740157480315
bound ['bound']
3.5137254901960784
bowel ['bowel']
3.515625
boxer ['boxer']
3.517509727626459
brace ['brace']
3.5193798449612403
braid ['braid']
3.5173745173745172
brain ['brain']
3.519230769230769
brake ['brake']
3.521072796934866
brand ['brand']
3.519083969465649
brash ['brash']
3.517110266159696
brass ['brass']
3.515151515151515
brave ['brave']
3.516981132075472
bravo ['bravo']
3.5150375939849625
brawl ['brawl']
3.5168539325842696
brawn ['brawn']
3.5186567164179103
bread ['bread']
3.516728624535316
break ['break']
3.5148148148148146
breed ['breed']
3.5166051660516606
briar ['briar']
3.514705882352941
bribe ['bribe']
3.5164835164835164
brick ['brick']
3.5182481751824817
bride ['bride']
3.52
brief ['brief']
3.5217391304347827
brine ['brine']
3.523465703971119
bring ['bring']
3.5251798561151078
brin

In [102]:
x=prob_grid(big_arr)

In [98]:
print(x[np.argmax(x)])
print(glist[np.argmax(x)])


5.885202744292758
soare


In [4]:
import numpy as np


big_arr=np.array(big_arr)

un_pat=np.unique(big_arr.reshape(big_arr.shape[0]**2,5),axis=0)


p=0
for i in range(len(un_pat)):
    p+=len(np.where(np.prod(big_arr == un_pat[i,:], axis = -1))[0])/(big_arr.shape[0])**2
print(p)

0.9999999999999991


In [24]:
play.tiles('homer','homer'

[2, 2, 2, 2, 2]

In [35]:
import numpy as np
ll=np.array([[6,5,4],[4,5,6],[4,5,6]])


print(np.where(np.prod(ll == [4,5,6], axis = -1)))



(array([1, 2]),)


In [ ]:
data = np.array( [  [1,2] , [1,3] ,[3,4], [1,2] , [0,9] ])

In [117]: np.where(np.prod(data == [1,2], axis = -1))
Out[117]: (array([0, 3]),)


False