In [ ]:
import numpy as np

import sys

sys.path.append('../')
sys.path.append('./')
sys.path.append('wbot/')
sys.path.append('WordleBot/wbot/')

from wbot import read,play


#load list containing every possible wordle answer
plist=read.word_list('possible')

#load numpy array containing every allowed wordle guess 
glist=read.word_list('allowed')


all_tiles=[]


#for each guess and possible answer pair simulate tiles and save results to array
for i, g in enumerate(glist):
    g_outcomes=[]
    for j,p in enumerate(plist):
        g_outcomes+=[play.tiles(p,g)]
    
    all_tiles+=[g_outcomes]
    
    if i%100==0:
        print(i)



all_tiles=np.array(all_tiles)

#save all tiles as compressed file
np.savez_compressed('all_tiles.npz',data=all_tiles)


In [1]:
import numpy as np

import sys

sys.path.append('../')
sys.path.append('./')
sys.path.append('wbot/')
sys.path.append('WordleBot/wbot/')

from wbot import read,play

glist=read.word_list('allowed')


In [4]:
print(np.where(np.array(glist)=='salet'))
print(np.where(np.array(glist)=='crane'))
print(np.where(np.array(glist)=='audio'))


(array([12489]),)
(array([8836]),)
(array([339]),)


In [8]:
import numpy as np

import sys

sys.path.append('../')
sys.path.append('./')
sys.path.append('wbot/')
sys.path.append('WordleBot/wbot/')

from wbot import read,play,solve

#load all tile combination for each guess word and true word pair
all_tiles=np.load('all_tiles.npz')['data']

#load list containing every possible wordle answer
plist=read.word_list('possible')

#load numpy array containing every allowed wordle guess 
glist=read.word_list('allowed')

#load the number of unique tile patterns given the starting guess is 'salet'
un_pat=np.unique(all_tiles[339,:,:],axis=0)


g_word=[]

#calculate the best second guess for possible pattern based on the maximum expected information
for pat in un_pat:
    

    tgrid,plist_=solve.reduce('audio',pat,all_tiles,np.array(plist),np.array(glist))

    info_grid=solve.info_grid(tgrid)

    guess=glist[np.argmax(info_grid)]
    
    g_word+=[guess]
    
    print(pat,guess)

#save unique patterns
np.save('audio_patterns.npy',un_pat)
#save best second guesses
np.save('audio_guess.npy',g_word,)

[0 0 0 0 0] terse
[0 0 0 0 1] torse
[0 0 0 0 2] crept
[0 0 0 1 0] trine
[0 0 0 1 1] veins
[0 0 0 1 2] gnarl
[0 0 0 2 0] relet
[0 0 0 2 1] cotan
[0 0 0 2 2] women
[0 0 1 0 0] beers
[0 0 1 0 1] derny
[0 0 1 0 2] women
[0 0 1 1 0] tiler
[0 0 1 1 1] dotes
[0 0 1 1 2] feens
[0 0 1 2 0] voted
[0 0 1 2 1] poled
[0 0 2 0 0] thurl
[0 0 2 0 1] gruel
[0 0 2 0 2] women
[0 0 2 1 0] resew
[0 0 2 1 1] women
[0 0 2 1 2] women
[0 0 2 2 0] women
[0 1 0 0 0] perst
[0 1 0 0 1] crest
[0 1 0 1 0] emits
[0 1 0 1 1] women
[0 1 0 2 0] slant
[0 1 1 0 0] cruet
[0 1 1 0 1] horns
[0 1 1 2 0] feens
[0 1 2 0 0] women
[0 1 2 2 0] women
[0 2 0 0 0] byrls
[0 2 0 0 1] rathe
[0 2 0 0 2] groma
[0 2 0 1 0] gecks
[0 2 0 2 0] cents
[0 2 0 2 2] women
[0 2 1 0 0] meths
[0 2 1 0 2] women
[0 2 1 1 0] clags
[0 2 1 2 0] clags
[0 2 2 0 0] bunde
[1 0 0 0 0] crest
[1 0 0 0 1] scran
[1 0 0 0 2] berms
[1 0 0 1 0] larnt
[1 0 0 1 1] women
[1 0 0 1 2] women
[1 0 0 2 0] canst
[1 0 0 2 2] poled
[1 0 1 0 0] drent
[1 0 1 0 1] umbra
[1 0 1 1 0